parameters:
#    acme_ia_front.example.class: Acme\IAFrontBundle\Example

services:
#    acme_ia_front.example:
#        class: %acme_ia_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
